### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by declension** [kratsg/pylibmagic#66]
First of all, thanks for the library, very useful!

[Python 3.12 is now out](https://docs.python.org/3.12/) :tada: 

In upgrading our CI matrix build to support this, we got breakage due to lack of `libmagic` again. Presumably this is now due to failing to install the `pylibmagic` wheel which [doesn't exist at 0.4.0](https://pypi.org/project/pylibmagic/0.4.0/#files)?

Could we add 3.12 to the build matrix? Happy to have a go at a PR if that helps

**Comment by kratsg** [comment]
Try [v0.5.0](https://pypi.org/project/pylibmagic/0.5.0/) and see if that works.

**Comment by declension** [comment]
> Try [v0.5.0](https://pypi.org/project/pylibmagic/0.5.0/) and see if that works.

Works like a charm - thanks!
